"""BUG-033: soma status must count rules merged into ~/.claude/CLAUDE.md.

install.sh / install.ps1 (claude platform) merge every rule into a single
CLAUDE.md instead of copying loose .md files. status used to glob the rules
directory for *.md excluding CLAUDE.md and, finding nothing, fell back to the
package's own genome/ — so a 1-rule CLAUDE.md reported the genome count.

Every test isolates HOME *and* USERPROFILE (BUG-010) and runs from an empty
project directory, without ``_root`` so platform detection actually runs.
"""
import argparse
import os
import re
import shutil
import subprocess
from pathlib import Path

import pytest

from soma_cli.status import run_status

REPO_ROOT = Path(__file__).resolve().parent.parent
GENOME = REPO_ROOT / "genome"
INSTALL_SH = REPO_ROOT / "install" / "install.sh"

INSTALL_HEADER = (
    "# Soma Governance Rules\n\n"
    "> Auto-generated by Soma. Do not edit directly.\n\n"
)


def _strip_frontmatter(text: str) -> str:
    lines = text.splitlines(True)
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                return "".join(lines[i + 1:])
    return text


def _install_format(*rule_paths: Path) -> str:
    """Reproduce install.sh's claude merge: header, then '---' + body per rule."""
    out = INSTALL_HEADER
    for p in rule_paths:
        out += "---\n\n" + _strip_frontmatter(p.read_text(encoding="utf-8")) + "\n"
    return out


def _genome_rules() -> list:
    """All rule files install.sh merges (find genome -name '*.md' | sort)."""
    return sorted(p for p in GENOME.rglob("*.md") if p.is_file())


@pytest.fixture
def env(tmp_path, monkeypatch):
    home = tmp_path / "home"
    (home / ".claude").mkdir(parents=True)
    proj = tmp_path / "proj"
    proj.mkdir()
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("USERPROFILE", str(home))
    monkeypatch.chdir(proj)
    return home / ".claude"


def _status(capsys) -> tuple:
    assert run_status(argparse.Namespace()) == 0
    out = capsys.readouterr().out
    m = re.search(r"Core rules:\s+(\d+) active", out)
    assert m, out
    return int(m.group(1)), out


def test_single_merged_rule_does_not_report_genome_count(env, capsys):
    (env / "CLAUDE.md").write_text(
        _install_format(GENOME / "providence.md"), encoding="utf-8")
    count, out = _status(capsys)
    assert count == 1, out
    # Heading maps back to the genome rule id so trigger counts line up.
    assert re.search(r"^\s+providence\s", out, re.M), out


def test_bom_prefixed_claude_md_is_detected(env, capsys):
    # Windows PowerShell 5.1 `Set-Content -Encoding UTF8` (install.ps1)
    # prepends a UTF-8 BOM; detection must not depend on its absence.
    (env / "CLAUDE.md").write_bytes(
        b"\xef\xbb\xbf" + _install_format(GENOME / "providence.md").encode("utf-8"))
    count, out = _status(capsys)
    assert count == 1, out


def test_merged_rule_plus_loose_files_are_summed(env, capsys):
    (env / "CLAUDE.md").write_text(
        _install_format(GENOME / "providence.md"), encoding="utf-8")
    (env / "alpha.md").write_text("# Alpha\n", encoding="utf-8")
    (env / "beta.md").write_text("# Beta\n", encoding="utf-8")
    count, out = _status(capsys)
    assert count == 3, out


def test_full_install_with_internal_horizontal_rules(env, capsys):
    """tdd-protocol bodies contain '---' + '## Gate N' — not new rules."""
    rules = _genome_rules()
    (env / "CLAUDE.md").write_text(_install_format(*rules), encoding="utf-8")
    (env / "extra.md").write_text("# Extra\n", encoding="utf-8")
    count, out = _status(capsys)
    assert count == len(rules) + 1, out
    assert len(re.findall(r"^\s+tdd-protocol\s", out, re.M)) == 1, out


def test_soma_header_without_rules_never_falls_back_to_genome(env, capsys):
    (env / "CLAUDE.md").write_text(INSTALL_HEADER, encoding="utf-8")
    count, out = _status(capsys)
    assert count == 0, out


def test_init_marker_block_counts_sections(env, capsys):
    """soma init format: <!-- SOMA:START --> with '## <stem>' sections."""
    block = (
        "My own notes.\n\n"
        "<!-- SOMA:START -->\n# Soma Governance Rules\n\n"
        "## alpha\n\n---\nid: alpha-rule\n---\n# Alpha\n\nBody.\n\n---\n\n"
        "## beta\n\n# Beta\n\nIntro.\n\n---\n\n## Metrics\n\nNot a rule.\n"
        "<!-- SOMA:END -->\n"
    )
    (env / "CLAUDE.md").write_text(block, encoding="utf-8")
    count, out = _status(capsys)
    assert count == 2, out
    assert re.search(r"^\s+alpha-rule\s", out, re.M), out
    assert re.search(r"^\s+beta\s", out, re.M), out


def test_init_marker_block_does_not_double_count_loose_copies(env, capsys):
    """soma init leaves the loose copies next to the merged block."""
    (env / "alpha.md").write_text("---\nid: alpha-rule\n---\n# Alpha\n",
                                  encoding="utf-8")
    (env / "beta.md").write_text("# Beta\n", encoding="utf-8")
    block = (
        "<!-- SOMA:START -->\n# Soma Governance Rules\n\n"
        "## alpha\n\n---\nid: alpha-rule\n---\n# Alpha\n\n---\n\n"
        "## beta\n\n# Beta\n"
        "<!-- SOMA:END -->\n"
    )
    (env / "CLAUDE.md").write_text(block, encoding="utf-8")
    count, out = _status(capsys)
    assert count == 2, out
    assert len(re.findall(r"^\s+alpha-rule\s", out, re.M)) == 1, out


def test_install_format_does_not_double_count_loose_copy(env, capsys):
    (env / "CLAUDE.md").write_text(
        _install_format(GENOME / "providence.md"), encoding="utf-8")
    shutil.copy(GENOME / "providence.md", env / "providence.md")
    count, out = _status(capsys)
    assert count == 1, out


def test_user_claude_md_without_soma_content_is_ignored(env, capsys):
    (env / "CLAUDE.md").write_text(
        "# My notes\n\n---\n\n# Another heading\n", encoding="utf-8")
    (env / "alpha.md").write_text("# Alpha\n", encoding="utf-8")
    count, out = _status(capsys)
    assert count == 1, out


@pytest.mark.skipif(os.name == "nt" or shutil.which("bash") is None,
                    reason="needs a POSIX bash to run install.sh")
def test_real_install_sh_claude_merge_plus_loose_files(env, capsys, tmp_path):
    """The exact BUG-033 repro: install.sh claude, then 2 loose .md files."""
    home = env.parent
    proc = subprocess.run(
        ["bash", str(INSTALL_SH), "claude"],
        cwd=str(tmp_path / "proj"), stdin=subprocess.DEVNULL,
        capture_output=True, text=True, timeout=120,
        env={**os.environ, "HOME": str(home), "USERPROFILE": str(home)},
    )
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert (env / "CLAUDE.md").is_file()
    (env / "alpha.md").write_text("# Alpha\n", encoding="utf-8")
    (env / "beta.md").write_text("# Beta\n", encoding="utf-8")
    count, out = _status(capsys)
    assert count == len(_genome_rules()) + 2, out


def test_bom_prefixed_loose_rule_uses_frontmatter_and_dedupes(env, capsys):
    """PowerShell 5.1 Set-Content -Encoding UTF8 BOM-prefixes loose copies."""
    (env / "alpha_loose.md").write_bytes(
        b"\xef\xbb\xbf" + b"---\nid: alpha-rule\n---\n# Loose Alpha\n")
    block = (
        "<!-- SOMA:START -->\n# Soma Governance Rules\n\n"
        "## alpha\n\n---\nid: alpha-rule\n---\n# Alpha\n"
        "<!-- SOMA:END -->\n"
    )
    (env / "CLAUDE.md").write_text(block, encoding="utf-8")
    count, out = _status(capsys)
    assert count == 1, out
    assert len(re.findall(r"^\s+alpha-rule\s", out, re.M)) == 1, out
    assert "alpha_loose" not in out, out
