"""soma completion — print a shell completion script for bash, zsh, or fish.

The script is generated at runtime by walking the argparse parser from
soma_cli.cli._build_parser(), so it can never drift from the real CLI.
Soma never edits dotfiles: the script goes to stdout and the user wires it
up themselves (see QUICKSTART.md, "Shell completion").

argparse has no public introspection API, so this reads ``parser._actions``
and ``_SubParsersAction`` — stable across every supported Python (3.9+).
"""
from __future__ import annotations

import argparse
import re

SHELLS = ("bash", "zsh", "fish")


# ── Parser model ────────────────────────────────────────────────────────────

class _Opt:
    def __init__(self, action: argparse.Action):
        self.strings = list(action.option_strings)
        self.help = _clean(action.help)
        self.takes_value = action.nargs != 0
        self.choices = [str(c) for c in action.choices] if action.choices else []


class _Cmd:
    def __init__(self, name: str, help_text: str, parser: argparse.ArgumentParser):
        self.name = name
        self.help = _clean(help_text)
        self.options: list[_Opt] = []
        self.positional_choices: list[str] = []
        for action in parser._actions:
            if action.help == argparse.SUPPRESS:
                continue
            if action.option_strings:
                self.options.append(_Opt(action))
            elif action.choices and not isinstance(action, argparse._SubParsersAction):
                self.positional_choices.extend(str(c) for c in action.choices)


def _clean(text) -> str:
    """ASCII-only, single-line help text (keeps cp1252 stdout safe)."""
    if not text or text == argparse.SUPPRESS:
        return ""
    text = str(text).replace("%%", "%")
    text = text.replace("\u2014", "-").replace("\u2013", "-")
    text = re.sub(r"\s+", " ", text)
    return text.encode("ascii", "ignore").decode("ascii").strip()


# Words emitted unquoted or inside shell word lists (command names, option
# strings, choices). Users eval the output, so anything outside this charset
# fails generation loudly instead of being escaped per shell.
_SAFE_WORD = re.compile(r"^-{0,2}[A-Za-z0-9][A-Za-z0-9._+-]*$")


def _check_words(cmd: _Cmd) -> None:
    words = [cmd.name] + cmd.positional_choices
    for o in cmd.options:
        words += o.strings + o.choices
    for w in words:
        if not _SAFE_WORD.match(w):
            raise ValueError(f"unsafe completion word: {w!r}")


def _model(parser: argparse.ArgumentParser) -> tuple[_Cmd, list[_Cmd]]:
    top = _Cmd(parser.prog, "", parser)
    commands: list[_Cmd] = []
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            helps = {a.dest: a.help for a in action._choices_actions}
            for name, sub in action.choices.items():
                commands.append(_Cmd(name, helps.get(name, ""), sub))
    for cmd in [top] + commands:
        _check_words(cmd)
    return top, commands


# ── bash ────────────────────────────────────────────────────────────────────

def _bash(prog: str, top: _Cmd, commands: list[_Cmd]) -> str:
    fn = "_" + re.sub(r"\W", "_", prog)
    top_words = [c.name for c in commands] + [s for o in top.options for s in o.strings]
    out = [
        f"# bash completion for {prog} -- generated by `{prog} completion bash`",
        f"{fn}() {{",
        "    local cur prev cmd i",
        '    cur="${COMP_WORDS[COMP_CWORD]}"',
        '    prev=""',
        '    [ "$COMP_CWORD" -gt 0 ] && prev="${COMP_WORDS[COMP_CWORD-1]}"',
        '    cmd=""',
        "    for ((i=1; i<COMP_CWORD; i++)); do",
        '        case "${COMP_WORDS[i]}" in',
        "            -*) ;;",
        '            *) cmd="${COMP_WORDS[i]}"; break ;;',
        "        esac",
        "    done",
        "    COMPREPLY=()",
        '    case "$cmd" in',
        '        "")',
        f"            COMPREPLY=($(compgen -W '{' '.join(top_words)}' -- \"$cur\"))",
        "            ;;",
    ]
    for cmd in commands:
        out.append(f"        {cmd.name})")
        value_opts = [o for o in cmd.options if o.takes_value]
        if value_opts:
            out.append('            case "$prev" in')
            for o in value_opts:
                pattern = "|".join(o.strings)
                if o.choices:
                    out.append(f'                {pattern}) COMPREPLY=($(compgen -W '
                               f"'{' '.join(o.choices)}'" ' -- "$cur")); return 0 ;;')
                else:
                    # Empty reply: `complete -o default` falls back to filenames.
                    out.append(f"                {pattern}) return 0 ;;")
            out.append("            esac")
        words = cmd.positional_choices + [s for o in cmd.options for s in o.strings]
        out.append(f"            COMPREPLY=($(compgen -W '{' '.join(words)}' -- \"$cur\"))")
        out.append("            ;;")
    out += [
        "    esac",
        "    return 0",
        "}",
        f"complete -F {fn} -o default {prog}",
        "",
    ]
    return "\n".join(out)


# ── zsh ─────────────────────────────────────────────────────────────────────

def _zq(text: str) -> str:
    """Escape for a single-quoted zsh word."""
    return text.replace("'", "'\\''")


def _zdesc(text: str) -> str:
    """Escape for an _arguments [description].

    Backslashes are stripped first so the only ones emitted are the ':'
    escapes (an unescaped ':' would end the description early).
    """
    text = text.replace("\\", "").replace("[", "(").replace("]", ")")
    return _zq(text.replace(":", "\\:"))


def _zsh_spec(o: _Opt) -> str:
    desc = f"[{_zdesc(o.help)}]"
    if o.takes_value:
        if o.choices:
            desc += f":{o.strings[-1].lstrip('-')}:({' '.join(o.choices)})"
        else:
            desc += ": :_default"
    if len(o.strings) == 1:
        return f"'{o.strings[0]}{desc}'"
    group = " ".join(o.strings)
    names = ",".join(o.strings)
    return f"'({group})'{{{names}}}'{desc}'"


def _zsh(prog: str, top: _Cmd, commands: list[_Cmd]) -> str:
    fn = "_" + re.sub(r"\W", "_", prog)
    out = [
        f"#compdef {prog}",
        f"# zsh completion for {prog} -- generated by `{prog} completion zsh`",
        "",
        f"{fn}() {{",
        "    local curcontext=\"$curcontext\" state line",
        "    typeset -A opt_args",
        "    _arguments -C \\",
    ]
    for o in top.options:
        out.append(f"        {_zsh_spec(o)} \\")
    out += [
        "        '1: :->cmds' \\",
        "        '*:: :->args'",
        "    case $state in",
        "        cmds)",
        "            local -a commands",
        "            commands=(",
    ]
    for cmd in commands:
        out.append(f"                '{cmd.name}:{_zq(cmd.help)}'")
    out += [
        "            )",
        f"            _describe -t commands '{prog} command' commands",
        "            ;;",
        "        args)",
        "            case $line[1] in",
    ]
    for cmd in commands:
        specs = [_zsh_spec(o) for o in cmd.options]
        if cmd.positional_choices:
            specs.append(f"'1: :({' '.join(cmd.positional_choices)})'")
        out.append(f"                {cmd.name})")
        if specs:
            out.append("                    _arguments \\")
            for i, spec in enumerate(specs):
                tail = " \\" if i < len(specs) - 1 else ""
                out.append(f"                        {spec}{tail}")
        out.append("                    ;;")
    out += [
        "            esac",
        "            ;;",
        "    esac",
        "}",
        "",
        "# Autoloaded from $fpath (#compdef) or sourced via eval: handle both.",
        f'if [ "$funcstack[1]" = "{fn}" ]; then',
        f'    {fn} "$@"',
        "else",
        f"    compdef {fn} {prog}",
        "fi",
        "",
    ]
    return "\n".join(out)


# ── fish ────────────────────────────────────────────────────────────────────

def _fq(text: str) -> str:
    """Single-quoted fish string."""
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _fish_opt(prog: str, cond: str, o: _Opt) -> str:
    parts = [f"complete -c {prog} -n {_fq(cond)}"]
    for s in o.strings:
        if s.startswith("--"):
            parts.append(f"-l {s[2:]}")
        elif len(s) == 2:
            parts.append(f"-s {s[1:]}")
        else:
            parts.append(f"-o {s[1:]}")
    if o.takes_value:
        if o.choices:
            parts.append(f"-x -a {_fq(' '.join(o.choices))}")
        else:
            parts.append("-r -F")
    if o.help:
        parts.append(f"-d {_fq(o.help)}")
    return " ".join(parts)


def _fish(prog: str, top: _Cmd, commands: list[_Cmd]) -> str:
    names = " ".join(c.name for c in commands)
    root_cond = f"not __fish_seen_subcommand_from {names}"
    out = [
        f"# fish completion for {prog} -- generated by `{prog} completion fish`",
        f"complete -c {prog} -f",
    ]
    for o in top.options:
        out.append(_fish_opt(prog, root_cond, o))
    for cmd in commands:
        line = f"complete -c {prog} -n {_fq(root_cond)} -a {cmd.name}"
        if cmd.help:
            line += f" -d {_fq(cmd.help)}"
        out.append(line)
    for cmd in commands:
        cond = f"__fish_seen_subcommand_from {cmd.name}"
        if cmd.positional_choices:
            out.append(f"complete -c {prog} -n {_fq(cond)} -a "
                       f"{_fq(' '.join(cmd.positional_choices))}")
        for o in cmd.options:
            out.append(_fish_opt(prog, cond, o))
    out.append("")
    return "\n".join(out)


# ── Entry points ────────────────────────────────────────────────────────────

_GENERATORS = {"bash": _bash, "zsh": _zsh, "fish": _fish}


def generate(parser: argparse.ArgumentParser, shell: str) -> str:
    """Return the completion script for ``shell`` derived from ``parser``."""
    if shell not in _GENERATORS:
        raise ValueError(f"Unsupported shell: '{shell}'. Choose from: {', '.join(SHELLS)}")
    top, commands = _model(parser)
    return _GENERATORS[shell](parser.prog, top, commands)


def run_completion(args: argparse.Namespace) -> int:
    """Print the completion script for args.shell to stdout."""
    from soma_cli.cli import _build_parser
    print(generate(_build_parser(), args.shell), end="")
    return 0
