"""Convert ``CellCandidate`` lists into cell markdown files.

All generated cells are written to ``vacuoles/`` regardless of
their ``proposed_type``, honouring the constraint that new cells
always start as vacuoles.
"""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import yaml

from soma_cli.genesis_scanner import CellCandidate


def generate_cells(
    candidates: list[CellCandidate],
    cells_dir: Path,
    dry_run: bool = False,
    force: bool = False,
) -> list[dict]:
    """Generate cell files from candidates.

    ALL cells are created as vacuoles/ regardless of proposed_type.
    Returns list of {path, name, action} dicts.
    """
    results: list[dict] = []
    vacuole_dir = cells_dir / "vacuoles"

    for candidate in candidates:
        filename = f"{candidate.name}.md"
        target = vacuole_dir / filename

        if target.is_symlink():
            results.append({"path": str(target), "name": candidate.name, "action": "skipped", "reason": "symlink"})
            continue

        if target.exists() and not force:
            results.append({
                "path": str(target),
                "name": candidate.name,
                "action": "skipped",
                "reason": "exists",
            })
            continue

        content = _render_cell(candidate)

        if dry_run:
            results.append({
                "path": str(target),
                "name": candidate.name,
                "action": "would_create",
                "content": content,
            })
        else:
            vacuole_dir.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            results.append({
                "path": str(target),
                "name": candidate.name,
                "action": "created",
            })

    return results


def _sanitize_frontmatter_value(val: str) -> str:
    """Collapse newlines and defang YAML document delimiters."""
    return " ".join(val.replace("---", "--").split())


def _sanitize_table_cell(val: str) -> str:
    """Escape pipes and collapse newlines for Markdown table cells."""
    return " ".join(val.split()).replace("|", "\\|")


def _render_cell(candidate: CellCandidate) -> str:
    """Render a CellCandidate as cell markdown with YAML frontmatter."""
    frontmatter = {
        "type": "vacuole",  # ALL cells start as vacuoles
        "proposed_type": _sanitize_frontmatter_value(candidate.proposed_type),
        "hypothesis": _sanitize_frontmatter_value(candidate.hypothesis),
        "prediction": _sanitize_frontmatter_value(candidate.prediction),
        "falsification": _sanitize_frontmatter_value(candidate.falsification),
        "target_paths": [_sanitize_frontmatter_value(p).replace('\\', '/') for p in candidate.target_paths],
        "enforcement": "advisory",
        "minimum_mode": "breeze",
        "tags": [_sanitize_frontmatter_value(t) for t in candidate.tags] + ["genesis-generated"],
        "created": str(date.today()),
        "genesis_confidence": round(candidate.confidence, 2),
        "expiry_sessions": 10,
        "expiry_days": 30,
    }

    fm_str = yaml.dump(frontmatter, default_flow_style=False, sort_keys=False)

    body = (
        f"## Vacuole: {candidate.hypothesis}\n"
        f"\n"
        f"> **Proposed organelle**: {candidate.proposed_type}"
        f" (pending promotion via evidence)\n"
        f"> **Genesis confidence**: {candidate.confidence:.0%}\n"
        f"\n"
        f"{candidate.hypothesis}\n"
        f"\n"
        f"### Prediction\n"
        f"{candidate.prediction}\n"
        f"\n"
        f"### Falsification Criteria\n"
        f"{candidate.falsification}\n"
        f"\n"
        f"### Evidence\n"
        f"```json\n"
        f"{json.dumps(candidate.evidence, indent=2)}\n"
        f"```\n"
    )
    return f"---\n{fm_str}---\n{body}"


def generate_report(candidates: list[CellCandidate], project_type: str) -> str:
    """Generate a human-readable organelle map (docs/organelles.md)."""
    groups: dict[str, list[CellCandidate]] = {}
    for c in candidates:
        groups.setdefault(c.proposed_type, []).append(c)

    type_emoji = {
        "wall": "🧱",
        "membrane": "🫧",
        "vacuole": "🟤",
        "chloroplast": "🟢",
        "plasmodesmata": "🔗",
    }

    sections: list[str] = []
    for ptype in ["wall", "membrane", "vacuole", "chloroplast", "plasmodesmata"]:
        if ptype not in groups:
            continue
        emoji = type_emoji.get(ptype, "")
        lines = [f"### {emoji} {ptype.title()}s\n"]
        for c in groups[ptype]:
            lines.append(
                f"| `{_sanitize_table_cell(c.name)}` | {c.confidence:.0%} | {_sanitize_table_cell(c.hypothesis)} |"
            )
        sections.append("\n".join(lines))

    header = (
        f"# Organelle Map\n\n"
        f"Auto-generated by `soma genesis` on {date.today()}.\n"
        f"Project type: {project_type}\n\n"
        f"| Name | Confidence | Hypothesis |\n"
        f"|------|-----------|------------|\n"
    )
    return header + "\n\n".join(sections)
